---
- name: Pull image from registry
  community.docker.docker_image:
    name: "{{ michae.components.jellyfin.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: started
    name: jellyfin
    image: "{{ michae.components.jellyfin.image }}"
    restart_policy: unless-stopped
    published_ports:
      - "{{ michae.components.jellyfin.port }}:8096"
    networks:
      - name: "{{ michae.network.name }}"
    volumes:
      - "{{ michae.config_dir }}/jellyfin/config:/config"
      - "{{ michae.config_dir }}/jellyfin/cache:/cache"
    mounts:
      - source: "{{ michae.components.jellyfin.media_dir }}"
        target: /media
        type: bind
