version: "3.7"

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=your_existing_db_host

volumes:
  nextcloud:
    driver: local
