FROM node:20-bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive

ARG SHINOBI_BRANCH=dev

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    ffmpeg \
    default-mysql-client \
    procps \
    && rm -rf /var/lib/apt/lists/*  # Clean up to reduce image size

RUN git clone --branch $SHINOBI_BRANCH https://gitlab.com/Shinobi-Systems/Shinobi.git /home/Shinobi

WORKDIR /home/Shinobi

RUN mv conf.sample.json conf.json && mv super.sample.json super.json

RUN npm install

COPY entrypoint.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 8080

CMD ["/start.sh"]

