# Stage 1: Build
FROM node:20-bullseye-slim AS build

ENV DEBIAN_FRONTEND=noninteractive

ARG SHINOBI_BRANCH=dev

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    default-mysql-client \
    procps \
    && rm -rf /var/lib/apt/lists/*  # Clean up to reduce image size

RUN git clone --branch $SHINOBI_BRANCH https://gitlab.com/Shinobi-Systems/Shinobi.git /home/Shinobi

WORKDIR /home/Shinobi

RUN mv conf.sample.json conf.json && mv super.sample.json super.json

RUN npm install

# Stage 2: Runtime
FROM node:20-bullseye-slim

WORKDIR /home/Shinobi

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*

COPY --from=build /home/Shinobi /home/Shinobi
COPY entrypoint.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 8080

CMD ["/start.sh"]
