version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/html:/usr/share/nginx/html
