---
- name: Pull image from registry
  community.docker.docker_image:
    name: "{{ michae.components.portainer.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: started
    name: portainer
    image: "{{ michae.components.portainer.image }}"
    command: --bind :9000 --http-enabled
    restart_policy: unless-stopped
    published_ports:
      - "{{ michae.components.portainer.port }}:9000"
    networks:
      - name: "{{ michae.network.name }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ michae.config_dir }}/portainer/data:/data"
