---
- name: Create configuration directories
  ansible.builtin.import_tasks: directories.yml
  become: true

- name: Install mandatory packages
  ansible.builtin.import_tasks: install-packages.yml
  become: true

# - name: Upgrade libseccomp2 to latest version (32-bit Debian)
#   ansible.builtin.import_tasks: debian-libseccomp-update.yml
#   become: true
#   when:
#     - ansible_facts.os_family == "Debian"
#     - ansible_facts.userspace_bits == '32'

- name: Install Docker
  ansible.builtin.import_tasks: install-docker.yml
  become: true
