---
- name: Pull image from registry
  community.docker.docker_image:
    name: "{{ michae.components.reverse_proxy.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: started
    name: nginx
    image: "{{ michae.components.reverse_proxy.image }}"
    restart_policy: unless-stopped
    published_ports:
      - 80:80
      - 443:443
    networks:
      - name: "{{ michae.network.name }}"
    volumes:
      - "{{ michae.config_dir }}/nginx/ssl:/etc/nginx/ssl/certs:ro"
      - "{{ michae.config_dir }}/nginx/sites:/etc/nginx/sites-enabled:ro"
      - "{{ michae.config_dir }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ michae.config_dir }}/nginx/proxy.conf:/etc/nginx/includes/proxy.conf:ro"
      - "{{ michae.config_dir }}/nginx/index.html:/usr/share/nginx/html/index.html:ro"
